services:
    nginx:
        container_name: ${APP_NAME}_nginx
        image: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./data/:/var/www
            - ./containers/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php
        networks:
            - example-app

    mysql:
        image: mysql
        container_name: ${APP_NAME}_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - example-app

    php:
        build:
            context: ./data
            dockerfile: ../containers/php/Dockerfile
        container_name: ${APP_NAME}_php
        working_dir: /var/www
        volumes:
            - ./data/:/var/www
            - ./containers/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - example-app

networks:
    example-app:
        driver: bridge

volumes:
    dbdata:
